### ISSUE TITLE
Can you  make  AIRBUS A380-800 Thai Airways, lauda air 767-300er, Airbus A380 Asiana Airlines ,Air Austral A380, Kingfisher Airlines A380 ,ANA A380, Cathay Pacific A380, Philippines Airlines A380,American Airlines A380, us air force A380, Us Airways a380 and Philippine Airlines 787-10

### ISSUE THREAD

**Issue by BlueWacki** [kolos26/GEOFS-LiverySelector#102]
![th](https://user-images.githubusercontent.com/115602546/197316528-3db29dbf-8df7-4d70-a421-38e806f0f1a3.jpg)
![th](https://user-images.githubusercontent.com/115602546/197316816-161f2548-e101-49ba-a3f9-1aca0d1fbd0d.jpg)
![th](https://user-images.githubusercontent.com/115602546/197386376-b77e0e52-4220-4bde-a7bc-fecd9d39b4a7.jpg)
![th](https://user-images.githubusercontent.com/115602546/199926853-46176286-c37b-4ada-a19c-9a71d5f4bbeb.jpg)
![1138e34e51bc161586fe88a585340e9f](https://user-images.githubusercontent.com/115602546/199927691-df1dea3b-3ca8-4f80-ab83-18e513ab623f.jpg)
![th](https://user-images.githubusercontent.com/115602546/199927764-4ff86ceb-8422-43fc-80c0-d9aca1f6097c.jpg)
![
![th](https://user-images.githubusercontent.com/115602546/199928666-4b8d9c6c-ba41-40cc-b432-a5b7702c79e5.jpg)
th](https://user-images.githubusercontent.com/115602546/199928546-8286b688-c634-4d4a-8b6d-fa0a32408af0.jpg)
![t
![th](https://user-images.githubusercontent.com/115602546/199928909-e59dcce8-d559-48c5-bac0-c5c7a37ee726.jpg)
![th](https://user-images.githubusercontent.com/115602546/199929045-360d613b-1ff9-4d05-8033-30f4c8589845.jpg)
h](https://user-images.githubusercontent.com/115602546/199928796-409970fd-afb5-4736-8415-b65c28ee833b.jpg)
![th](https://user-images.githubusercontent.com/115602546/199929457-5882489f-aec5-4322-92c8-f8a6663316a8.jpg)
![th](https://user-images.githubusercontent.com/115602546/199933497-88b9b771-cbbc-4e9a-a955-da8ff4e2367b.jpg)
![th](https://user-images.githubusercontent.com/115602546/200165749-ca00dc63-626c-4ff6-8e6f-b4fbe3c0742c.jpg)

**Comment by Ryubunao** [comment]
This seems pretty hard so idk

**Comment by BoeingBus747** [comment]
I will try to make the thai one

**Comment by Egan-31** [comment]
hi, i'm already working on the thai, so please don't start it there is no interest doing it twice

**Comment by iuhairways** [comment]
i will make lauda

**Comment by kolos26** [comment]
Sorry for don't replay earlier, I was working on other projects. I'm mostly doing the coding part, so the deawing is mostly done by contributors. If you wold like to try it we will help you of course.

**Comment by Ryubunao** [comment]
Btw can you add the windows and doors decals in the A220 & A319 map? Cuz I idk where to put logos and texts correctly without placing them in the right place, and also make outlines for B767, B757, A350-1000 & A350-900, cuz idk where can I put the logo since I can't find the right spot in the tail section

**Comment by BlueWacki** [comment]
pls

**Comment by BoeingBus747** [comment]
> Btw can you add the windows and doors decals in the A220 & A319 map? Cuz I idk where to put logos and texts correctly without placing them in the right place, and also make outlines for B767, B757, A350-1000 & A350-900, cuz idk where can I put the logo since I can't find the right spot in the tail section

https://ibb.co/w71QPdv, https://ibb.co/0YLmNkp and I'm making a map for those aircrafts rn

**Comment by BlueWacki** [comment]
not the A319 and A220

**Comment by BlueWacki** [comment]
i am a neko

**Comment by BoeingBus747** [comment]
> not the A319 and A220

That's a uv map, paste it on the map to see where the windows/doors are

**Comment by Ryubunao** [comment]
> i am a neko

why r u here??

**Comment by BlueWacki** [comment]
uh because i am Cute

**Comment by Ryubunao** [comment]
> uh because i am Cute

😳😳😳

**Comment by BlueWacki** [comment]
https://www.roblox.com/users/1779858466/profile

**Comment by BlueWacki** [comment]
but is now air austral a380

**Comment by BlueWacki** [comment]
LOL DEEZ NUTS!

**Comment by Ryubunao** [comment]
bruh💀

**Comment by BlueWacki** [comment]
is a Hi Fly A380

**Comment by BlueWacki** [comment]
,ANA A380

**Comment by BlueWacki** [comment]
hii

**Comment by BlueWacki** [comment]
are u guys online??

**Comment by BlueWacki** [comment]
can you do that?😔

**Comment by githubuser589** [comment]
bros actually 8 💀

**Comment by Ryubunao** [comment]
> bros actually 8 💀

💀💀💀

**Comment by BlueWacki** [comment]
Why?

**Comment by BoeingBus747** [comment]
Can someone close this "issue"?

**Comment by BlueWacki** [comment]
No!😭

**Comment by BlueWacki** [comment]
Uh no?

**Comment by PilotKetchum2002** [comment]
> Uh no?

#235

**Comment by BlueWacki** [comment]
a in meet

**Comment by BoeingBus747** [comment]
"Can someone close this issue?"

**Comment by BlueWacki** [comment]
NO!!

**Comment by BoeingBus747** [comment]
Bruh

**Comment by PilotKetchum2002** [comment]
> a in meet
[BoeingBus747] Say That You Can Close The Issue

**Comment by BlueWacki** [comment]
> [BoeingBus747] Say That You Can Close The Issue
SHUT UP!!

**Comment by FreedomAirways** [comment]
> > [BoeingBus747] Say That You Can Close The Issue
> > SHUT UP!!

Why?

**Comment by githubuser589** [comment]
> "Can someone close this issue?"

even better, can someone get this kid off of github aswell?

**Comment by BoeingBus747** [comment]
true

**Comment by BlueWacki** [comment]
stop!!

**Comment by BoeingBus747** [comment]
At least it's finally closed
