### ISSUE TITLE
Jet2 757 livery. 

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#11]
![bv j n](https://user-images.githubusercontent.com/103064103/186951712-e5c6fddf-94df-493a-98db-9ff044d28550.jpg)
so the engines and winglets should have text but idk where to put

**Comment by kolos26** [comment]
I will figure it out for you tomorrow. (Now at me its quite late)

**Comment by iuhairways** [comment]
oki

**Comment by kolos26** [comment]
![757](https://user-images.githubusercontent.com/77933334/187020232-f3c6d580-ac46-4a2c-b222-e96ae75252d5.png)
I have find the winglets. The engines are half-half of the other part. 

I forgot to tell that the bottom of the texture (under the fuselage) needs to be white for every texture.

**Comment by kolos26** [comment]
The left winglet on the image is the left outer-right inner, the right one is the right outer, left inner.

**Comment by iuhairways** [comment]
ok

**Comment by iuhairways** [comment]
is one flipped???? @kolos26
