### ISSUE TITLE
Urgent question

### ISSUE THREAD

**Issue by githubuser589** [kolos26/GEOFS-LiverySelector#14]
Hello, who or where did you get the Ryanair 737-700 livery from?

I am the creator of that livery, and I DID NOT give anyone permission to use it.

Thanks

**Comment by kolos26** [comment]
Thanks, I fixed your China Eastern and Ethiopian textures for this addon.

**Comment by Ariakim-Taiyo** [comment]
Yw! feel free to reach out with any questions you may have.

**Comment by kolos26** [comment]
Thanks for your kind help. There might be some around the new aircrafts yet to come. Its good to see what a big project, and great community grew out in the last weeks. And it only started with my blurry imagination to put every liveries together and about twenty lines of code that played in the first round.

**Comment by githubuser589** [comment]
> This is false. I am the author of the 737-700 Ryanair livery in my livery changer addon. It was the first livery feature. There is a 737 max ryanair livery in multiliveries that I did not make, though. If you are using IUH's modification, i am not sure how many original files are still intact so just be aware.
> 
> Also, You're absolutely free to use my code and textures, they're open-source for a reason lol.

Sorry for not being clear, I was talking about a different Ryanair livery that I made. It is shown in this video: https://youtu.be/3i5sZOgSG8U 

I do believe it was in IUH’s liverychanger for some time

**Comment by kolos26** [comment]
> > This is false. I am the author of the 737-700 Ryanair livery in my livery changer addon. It was the first livery feature. There is a 737 max ryanair livery in multiliveries that I did not make, though. If you are using IUH's modification, i am not sure how many original files are still intact so just be aware.
> > Also, You're absolutely free to use my code and textures, they're open-source for a reason lol.
> 
> Sorry for not being clear, I was talking about a different Ryanair livery that I made. It is shown in this video: https://youtu.be/3i5sZOgSG8U
> 
> I do believe it was in IUH’s liverychanger for some time

Nevermind, i made a new one yesterday, so i think now it's ok fot everybody

**Comment by Ariakim-Taiyo** [comment]
> > This is false. I am the author of the 737-700 Ryanair livery in my livery changer addon. It was the first livery feature. There is a 737 max ryanair livery in multiliveries that I did not make, though. If you are using IUH's modification, i am not sure how many original files are still intact so just be aware.
> > Also, You're absolutely free to use my code and textures, they're open-source for a reason lol.
> 
> Sorry for not being clear, I was talking about a different Ryanair livery that I made. It is shown in this video: https://youtu.be/3i5sZOgSG8U
> 
> I do believe it was in IUH’s liverychanger for some time

Ah i see, yeah i didn't make that one. thx for clarifying
