### ISSUE TITLE
Jet2 757 livery (is good now)

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#15]
![dhjzdfsuddewrisgruaeiviveifvws_kcbsicawiufhsziuvaisfcsiavbukfbvdvbseiugiedgilusehgvilushegkisdhxvkishvsvluvysgrgvkursehgvkuegfefesufvaekvgfesuvg _ dfn tj tf mf mn fyhj rt nrt j nyum jpg](https://user-images.githubusercontent.com/103064103/187622414-399f9464-26f3-4d73-9573-cd6a14452dd3.jpg)

**Comment by iuhairways** [comment]
@kolos26

**Comment by kolos26** [comment]
Thanks for your work, added to database.
