### ISSUE TITLE
REQUEST: Qantas Airbus A380-800 - R E X   D A S H E R (FIXED)

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#152]
![qantasA380RexDasher](https://user-images.githubusercontent.com/107557660/200805810-ad001410-a228-499d-accc-9dea7bbca091.jpg)

Dear Kolos26 Please Release My Livery Thanks I Resized It!

**Comment by iuhairways** [comment]
why is it playmobil tho

**Comment by PilotKetchum2002** [comment]
> why is it playmobil tho

I Think It's From The 2019 Film Playmobil: The Movie
