### ISSUE TITLE
GULF AIR A319

### ISSUE THREAD

**Issue by izem-bro-emiz** [kolos26/GEOFS-LiverySelector#168]
![bbb](https://user-images.githubusercontent.com/115069627/201522459-11c58cda-8f97-475d-abca-3946070e946e.png)

**Comment by BoeingBus747** [comment]
Are you serious mate?

**Comment by izem-bro-emiz** [comment]
i didnt get it

**Comment by izem-bro-emiz** [comment]
sorry if there is any problem with the aircraft

**Comment by BoeingBus747** [comment]
It's a FICTIONAL livery and I'm pretty sure kolos doesn't accept those

**Comment by FreedomAirways** [comment]
> It's a FICTIONAL livery and I'm pretty sure kolos doesn't accept those

And the text doesn't need to be flipped

**Comment by izem-bro-emiz** [comment]
ok

**Comment by izem-bro-emiz** [comment]
> 

no its not, its real
![image](https://user-images.githubusercontent.com/115069627/202917460-f84975f6-aeef-4e1c-8e83-b2696981f957.png)

**Comment by BoeingBus747** [comment]
> > 
> 
> no its not, its real ![image](https://user-images.githubusercontent.com/115069627/202917460-f84975f6-aeef-4e1c-8e83-b2696981f957.png)

Bruh, just let me make it then you're is completely inaccurate

**Comment by BoeingBus747** [comment]
> > > 
> > 
> > 
> > no its not, its real ![image](https://user-images.githubusercontent.com/115069627/202917460-f84975f6-aeef-4e1c-8e83-b2696981f957.png)
> 
> A) Yours is completely inaccurate
> B) That is an a320 not a319

**Comment by izem-bro-emiz** [comment]
Since we cannot add in a320, i am adding it in a319

**Comment by izem-bro-emiz** [comment]
wdym inaccurate
