### ISSUE TITLE
REQUEST: Cebu Pacific B787-9 (Qantas Design)

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#179]
![CebPac787QantasHybrid 1](https://user-images.githubusercontent.com/107557660/202642006-d84fb650-7a28-4fa9-ad48-617ed0047aa4.png)

**Comment by Ryubunao** [comment]
Am I hallucinating?

**Comment by githubuser589** [comment]
You have to be joking.

> ![CebPac787QantasHybrid 1](https://user-images.githubusercontent.com/107557660/202642006-d84fb650-7a28-4fa9-ad48-617ed0047aa4.png)
