### ISSUE TITLE
ups 767

### ISSUE THREAD

**Issue by airgeorge** [kolos26/GEOFS-LiverySelector#19]
i resized the image and ended up with this,just ask me and i can see what i can do.
also sorry for the bad lines,i can fix that too. ![image](https://user-images.githubusercontent.com/112053353/188039230-5ae0fb1a-6ea5-43b4-a17f-478d017cc79f.png)

**Comment by kolos26** [comment]
Thanks for your work! The textures must be used in the original size of the map, so for the 767 it's 1024*1024px. You also need to keep the white parts on the bottom of the file.

**Comment by airgeorge** [comment]
ok,thank you!

**Comment by airgeorge** [comment]
here is the original photo ask me if you want me to fix the lies. ![image](https://user-images.githubusercontent.com/112053353/188222508-b84f9c4a-dd70-47c5-8cbb-0c2614857cbc.png)

**Comment by kolos26** [comment]
If this version is fine for you now, i can upload it, or if you would like to work more on the lines I will wait the new version

**Comment by airgeorge** [comment]
im going to make Fedex 757 then i will work on the lines because it looked liked a 3 year old drew them.

**Comment by kolos26** [comment]
It's fine. Randomgeofsplayer made a fedex 767 so they will look well together
