### ISSUE TITLE
REQUEST: Korean Air Boeing 787-9 Dreamliner  R E X  D A S H E R

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#197]
![Korean_AirRexDasher](https://user-images.githubusercontent.com/107557660/204127668-6ca68580-e372-4408-a65b-ac8abdd7b46b.png)

**Comment by Aviation-Enthusiast** [comment]
Why do you just mix an airline and Rex Dasher all the time

**Comment by PilotKetchum2002** [comment]
> Why do you just mix an airline and Rex Dasher all the time

That's Why I Just Loved This!

**Comment by BoeingBus747** [comment]
I'm getting tired of Rex-Dasher liveries
