### ISSUE TITLE
A359 map

### ISSUE THREAD

**Issue by randomgeofsplayer** [kolos26/GEOFS-LiverySelector#2]
could you send the map for a359 liveries? I've got a few I wanna try.

**Comment by kolos26** [comment]
The easiest way is just repaint this: [https://www.geo-fs.com/backend/aircraft/repository/GXD05OQ_166617_239/texture.png](https://www.geo-fs.com/backend/aircraft/repository/GXD05OQ_166617_239/texture.png).

![image](https://user-images.githubusercontent.com/77933334/185624675-ce1ccdc8-5e10-4df3-887b-3eed048c0289.png)

As you can see on the screenshot the front window is somewhere in front of that logo on the left. Every graphics that runs through the nose needs to go to the side of the image.

I will try to make a proper map, but it's hard to find the edges in 2d.

Thanks for your work!
