### ISSUE TITLE
LIVERY REQUEST: Qantas Airbus A380-800 (Old Livery)

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#203]
![qantas-airways-airline-qantas-identity-design-79628-adeevee](https://user-images.githubusercontent.com/107557660/204943106-67cdd4b6-774b-45f0-a742-d1fc233c344b.jpg)

![QantasA380 (Old) (3)](https://user-images.githubusercontent.com/107557660/204943052-cf6550e6-52b4-4f7b-83e7-70f858195555.jpg)

**Comment by BlueWacki** [comment]
https://github.com/kolos26/GEOFS-LiverySelector/issues/206

**Comment by PilotKetchum2002** [comment]
YES FINALLY WE APPROVED MY OLD DESIGN THANKS KOLOS26!
