### ISSUE TITLE
LIVERY REQUEST: Korean Air Boeing B787-9 Dreamliner - Bluey

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#204]
![KoreanAirBluey787 (3)](https://user-images.githubusercontent.com/107557660/205050094-7c7ff3fc-becf-437f-bcdb-2675e6cc3995.png)

**Comment by iuhairways** [comment]
how old are u

**Comment by iuhairways** [comment]
you just sending kids tv characters on exsisting liveries

**Comment by PilotKetchum2002** [comment]
> how old are u

20

**Comment by BlueWacki** [comment]
24

**Comment by BlueWacki** [comment]
i like it!
