### ISSUE TITLE
FICTIONAL LIVERY REQUEST: Korean Air A380-800 Bluey's Big Play Livery

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#212]
![Disney+KoreanAirBlueysBigPlay](https://user-images.githubusercontent.com/107557660/205920025-ba1a41b6-c42b-4ae5-beb1-49b2fa977425.png)

![KoreanA380BlueysBigPlay (3)](https://user-images.githubusercontent.com/107557660/205917687-aa8f74cc-f468-4d21-9014-48134d7756fd.png)

The Livery Is Only For Fictional Or Concept
Don't Disrespect My Livery Or Else!

It was announced that a stage show based on Bluey was being developed in November 2019.
The live stage show, titled Bluey's Big Play, toured in fifty theatres around Australia and featured the characters from the series
The tour was initially scheduled to begin in May 2020, but was delayed due to restrictions relating to the COVID-19 pandemic.
After eased restrictions, two preview performances were held at the Canberra Theatre Centre
Bluey's Big Play also toured the United States, debuting at the Hulu Theater at Madison Square Garden in November 2022.
A balloon of the Bluey character appeared at Macy's Thanksgiving Day Parade in November 2022.

![blueysbigplay_77259KAL (1)](https://user-images.githubusercontent.com/107557660/205948299-d04132b5-d390-4cc8-8902-fbff35413cf4.png)

**Comment by githubuser589** [comment]
Please stop mixing a random kid’s cartoon with a random airline, it’s getting tiring.

**Comment by FreedomAirways** [comment]
> Please stop mixing a random kid’s cartoon with a random airline, it’s getting tiring.

Me too

**Comment by PilotKetchum2002** [comment]
> > Please stop mixing a random kid’s cartoon with a random airline, it’s getting tiring.
> 
> Me too

STFU!

**Comment by PilotKetchum2002** [comment]
> Please stop mixing a random kid’s cartoon with a random airline, it’s getting tiring.

I’VE HAD ENOUGH OF BASHING MY LIVERIES! GET OUT NOW!

YOU GUYS ARE A NEFFEX SUPPORTERS!

**Comment by PilotKetchum2002** [comment]
@githubuser589 & @FreedomAirways 
YOU GUYS ARE THE WORST

GET OUT DELETE YOUR TWO COMMENTS NOW!

**Comment by BlueWacki** [comment]
ok

**Comment by BlueWacki** [comment]
SHUT UP THE F*CK UP! githubuser589 AND! FreedomAirways!😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡
