### ISSUE TITLE
the A320214 is nonworking links

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#23]
heer are good links 
easyJet carrot- https://raw.githubusercontent.com/iuhairways/a320214/main/easyjet.jpg
AliTalia- https://raw.githubusercontent.com/iuhairways/a320214/main/alitalia.png
House livrey- https://raw.githubusercontent.com/iuhairways/a320214/main/a320.jpg

**Comment by kolos26** [comment]
I have some problems with this aircraft, something can be wrong with the map. The correct size is 2048*2048px, but the parts are somehow in the wrong places. We should try to figure it out, or ask the creator to check out if the map is correct.

Thanks for your help in this project. Kolos26

**Comment by kolos26** [comment]
I prepared this experimental texture file, if you wanna try it

![a320-2048](https://user-images.githubusercontent.com/77933334/189363106-c7d465e3-e5f6-4e9c-b2d2-c7746f9e4321.jpg)

**Comment by iuhairways** [comment]
ok thanks!

**Comment by iuhairways** [comment]
@kolos26 try this https://raw.githubusercontent.com/iuhairways/a320214/main/test.jpg

**Comment by iuhairways** [comment]
wait i will try too

**Comment by kolos26** [comment]
The problem is the parts are totally in the wrong place.

![Képernyőkép 2022-09-09 183448](https://user-images.githubusercontent.com/77933334/189398657-721df4b7-b408-452e-a895-195c3cc0449f.png)

**Comment by kolos26** [comment]
And Idk why

**Comment by iuhairways** [comment]
oh

**Comment by iuhairways** [comment]
move up the body abit

**Comment by kolos26** [comment]
But there is the end of the texture file. Spice wrote a few months ago that he needs to remap the whole plane in blender. I think, we can't do it alone.

**Comment by iuhairways** [comment]
hmm ok
i do have some of the previous maps we could try

**Comment by kolos26** [comment]
Wait a minute. Can you remember what was the original size of the texture you've uploaded to this post: [https://github.com/Spice9/Geofs-Multiliveries/issues/13](https://github.com/Spice9/Geofs-Multiliveries/issues/13)???
I think it will work, in the good size

**Comment by iuhairways** [comment]
![image](https://user-images.githubusercontent.com/103064103/189403640-07f09a6a-c05f-47e6-871f-c21c08da2e0e.png)
![image](https://user-images.githubusercontent.com/103064103/189403758-0c3ee85b-07f7-4eff-adff-6967cc034f7e.png)
![image](https://user-images.githubusercontent.com/103064103/189403839-e2d19125-ec4d-4c5a-aa56-6d6293ddfb79.png)

**Comment by kolos26** [comment]
THX I'm trying theese

**Comment by iuhairways** [comment]
this is da ML one https://user-images.githubusercontent.com/103064103/169350570-e88301c6-0890-4e36-b6d3-70b753eaa621.png

**Comment by kolos26** [comment]
thanks

**Comment by iuhairways** [comment]
have you got it to work

**Comment by kolos26** [comment]
not yet

**Comment by iuhairways** [comment]
oh
did the liveries even change?

**Comment by kolos26** [comment]
yes, but the texture is not aligned

**Comment by iuhairways** [comment]
oh

lol on a320neo 
![image](https://user-images.githubusercontent.com/103064103/189409218-0fd66f17-fd5d-4fc1-a178-c9f39b212151.png)

**Comment by iuhairways** [comment]
> yes, but the texture is not aligned

screen shot?

**Comment by iuhairways** [comment]
@kolos26

**Comment by kolos26** [comment]
Sorry, I'm here, I have about 6 different widows, and i'm totally lost
I just cannot guess the size because 2048 is the maximum, but it looks too small on the plane. I think we should ask Spice9 for some ideas.

**Comment by iuhairways** [comment]
> Sorry, I'm here, I have about 6 different widows, and i'm totally lost I just cannot guess the size because 2048 is the maximum, but it looks too small on the plane. I think we should ask Spice9 for some ideas.

@kolos26 try 4096

**Comment by kolos26** [comment]
too big, after 2048 it throws an error

**Comment by iuhairways** [comment]
oh

**Comment by iuhairways** [comment]
did you join thi diskord

**Comment by kolos26** [comment]
no, I'm only avaliable on github

**Comment by iuhairways** [comment]
ok

**Comment by kolos26** [comment]
But now I need to go, sorry. I will try again tomorrow. Bye

**Comment by iuhairways** [comment]
> But now I need to go, sorry. I will try again tomorrow. Bye

ok me to

**Comment by iuhairways** [comment]
bye bye

**Comment by kolos26** [comment]
I think we can't do this, until the a320-214 rework arrives, that will have new texture map. Sorry, about that, I hope it will arrive soon.

**Comment by iuhairways** [comment]
> I think we can't do this, until the a320-214 rework arrives, that will have new texture map. Sorry, about that, I hope it will arrive soon.

ok
