### ISSUE TITLE
kolos26, please fix my citilink atr 72

### ISSUE THREAD

**Issue by bajushd** [kolos26/GEOFS-LiverySelector#236]
livery atr 72 citilink not working. please fixed it

**Comment by bajushd** [comment]
![ATR-72 Citilink](https://user-images.githubusercontent.com/109839447/207086046-e6e28539-4538-443f-aaf3-de137304dfa5.png)

**Comment by kolos26** [comment]
Thank you for letting me know that! I've fixed it.

**Comment by bajushd** [comment]
thanks
