### ISSUE TITLE
QUESTION: Any Ideas To Find A Basemap Of Boeing 777-300ER By LRX So I Can Make The Philippine Airlines Livery?

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#261]
![PAL-Fleet-Page541x460pxB777](https://user-images.githubusercontent.com/107557660/210092276-a239ee72-a519-432d-a1ab-23204b816c41.jpg)

![ANZ B777](https://user-images.githubusercontent.com/107557660/210092515-c827f9bf-fa2a-4932-babb-b189b52a8831.png)

**Comment by kolos26** [comment]
I asked lrx for permission, but I didn't get it, so we can't do liveries for that. The 777-200 by Throwaway8407, will probably be supported

**Comment by FreedomAirways** [comment]
> I asked lrx for permission, but I didn't get it, so we can't do liveries for that. The 777-200 by Throwaway8407, will probably be supported

What 772?

**Comment by kolos26** [comment]
It's not released yet, it's still under developement. Scroll this down and you will find some very nice pics about how it will look like. https://geofs.fandom.com/f
