### ISSUE TITLE
WHY WOULD YOU RATHER APPROVE MY BIRTHDAY LIVERIES CAUSE THEY'RE PERFECT!

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#296]
#276
#286
#279
#268
#275

**Comment by PilotKetchum2002** [comment]
I DEMAND @Burner To Kick Out Pls

**Comment by PilotKetchum2002** [comment]
I DEMAND @Burner7 For Destroying My Projects

**Comment by githubuser589** [comment]
**"fake"** and **"purely fictional"** basically mean the exact same thing 💀

**Comment by FreedomAirways** [comment]
> #276 #286 #279 #268 #275

Bruh, "fake" and "purely fictional" mean the same thing

**Comment by PilotKetchum2002** [comment]
@FreedomAirways & @githubuser589 JUST BLAME & KICK OUT @Burner7 CAUSE HE DONT LIKE

**Comment by PilotKetchum2002** [comment]
> > #276 #286 #279 #268 #275
> 
> Bruh, fake and purely fictional mean the same thing

Ah Alright Same! 💀💀💀💀💀💀💀💀💀💀

**Comment by PilotKetchum2002** [comment]
> > #276 #286 #279 #268 #275
> 
> Bruh, fake and purely fictional mean the same thing

why Am I Kicking Out The Discord Server Of Multiliveries?

**Comment by FreedomAirways** [comment]
> > > #276 #286 #279 #268 #275
> > 
> > 
> > Bruh, fake and purely fictional mean the same thing
> 
> why Am I Kicking Out The Discord Server Of Multiliveries?

I think because three of your liveries did not pass #voting
