### ISSUE TITLE
QUESTION: Why Is Not Approved My Liveries?

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#297]
![List](https://user-images.githubusercontent.com/107557660/218538075-bbb35e7e-c1dc-41b6-8806-7ca1fbb05502.png)

**Comment by FreedomAirways** [comment]
Maybe kolos26 is not fan of fictional liveries, idk

**Comment by PilotKetchum2002** [comment]
> Maybe kolos26 is not fan of fictional liveries, idk

No Idea @FreedomAirways
No Ideas BTW Kolos Just Apporved The Clearer Version Of Korean Air A380
