### ISSUE TITLE
Can somebody give me the DHC-6 Twin Otter map?

### ISSUE THREAD

**Issue by FreedomAirways** [kolos26/GEOFS-LiverySelector#298]

**Comment by PilotKetchum2002** [comment]
I Think Kolos Is Busy Right Now!

**Comment by FreedomAirways** [comment]
> I Think Kolos Is Busy Right Now!

Ok, i'll wait

**Comment by kolos26** [comment]
The Twin Otter is mad up from 4 texture files
geo-fs.com/models/aircraft/premium/dhc6/2_0.jpg - main section of the fuselage
geo-fs.com/models/aircraft/premium/dhc6/3_0.jpg - tail and end of the fuselage (the rudder and the vstab is placed in the middle)
geo-fs.com/models/aircraft/premium/dhc6/5_0.jpg - like the previous just mirrored for the other side
geo-fs.com/models/aircraft/premium/dhc6/4_0.jpg - engine

I hope this help you.
Kind regards, Kolos

**Comment by FreedomAirways** [comment]
> The Twin Otter is mad up from 4 texture files geo-fs.com/models/aircraft/premium/dhc6/2_0.jpg - main section of the fuselage geo-fs.com/models/aircraft/premium/dhc6/3_0.jpg - tail and end of the fuselage (the rudder and the vstab is placed in the middle) geo-fs.com/models/aircraft/premium/dhc6/5_0.jpg - like the previous just mirrored for the other side geo-fs.com/models/aircraft/premium/dhc6/4_0.jpg - engine
> 
> I hope this help you. Kind regards, Kolos

Ok, thank you
