### ISSUE TITLE
QUESTION: Why Am I Not Inviting Of Discord Server Of Multiliveries

### ISSUE THREAD

**Issue by PilotKetchum2002** [kolos26/GEOFS-LiverySelector#305]
![Whoops](https://user-images.githubusercontent.com/107557660/222840024-860cba83-2a07-4c4b-b350-de29039e649b.png)

**Comment by FreedomAirways** [comment]
> ![Whoops](https://user-images.githubusercontent.com/107557660/222840024-860cba83-2a07-4c4b-b350-de29039e649b.png)

You're blacklisted because three of your liveries didn't pass #voting (i am NOT the one who decide this, i am JUST A CONTRIBUTOR)

**Comment by PilotKetchum2002** [comment]
> > ![Whoops](https://user-images.githubusercontent.com/107557660/222840024-860cba83-2a07-4c4b-b350-de29039e649b.png)
> 
> You're blacklisted because three of your liveries didn't pass #voting (i am NOT the one who decide this, i am JUST A CONTRIBUTOR)

Can You Unblacklist Me!

**Comment by Ariakim-Taiyo** [comment]
Don't quite know how this has anything to do with LS but ok
