### ISSUE TITLE
Liveries were "pushed back"

### ISSUE THREAD

**Issue by CharlieDelta28** [kolos26/GEOFS-LiverySelector#307]
Hello @kolos26 

I have a sort of bug report to make.

Liveries on the 787-9 (didn't check the 787-10, but it might be concerned as well) and some liveries on the A320neo (the regular Lufthansa being one) appeared to have been slightly pushed back, as there now is a white stripe appearing on the from of Vertical stabiliser. I don't know if you can fix this yourself, but please focus on the 787-9 as it concerns most liveries (I do think all liveries have been pushed back, but some which are based on white, like Air France are obviously not as affected)

Thanks in advance, as I know you are very committed and reactive.

Sincerely,

Charlie Delta

**Comment by kolos26** [comment]
Thank you for searching bugs in the program! I have taken a look on those liveries, and those small grey stuff is the basically part of the deicing sytsem on the real plane, so we don't need to do anything with that just enjoying it. :)
