### ISSUE TITLE
i couldnt get it to work 

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#31]
![image](https://user-images.githubusercontent.com/103064103/192024208-f0949e9e-407a-4150-a2bf-04480b5717d9.png)
so i build my own:
![image](https://user-images.githubusercontent.com/103064103/192024349-4a2c2f5c-1b89-47f0-a6d6-4002ed167707.png)
but then: 
![image](https://user-images.githubusercontent.com/103064103/192024693-855438f7-9573-477d-abb8-9f81795a60ce.png)
no liveries appear on the game

**Comment by kolos26** [comment]
Hi,

You closed, the aircraft object too early. The other stuff must be inside that.

`{
	"aircrafts": {
		"4": {
			"mode": 3,
			"parts": [0],
			"liveries": [{
					"name": "TUI New",
					"texture": "https://i.ibb.co/kXZ66Z3/tui737new.jpg"
				},
				{
					"name": "Transavia",
					"texture": "https://i.ibb.co/Dts72Wj/tra737.png"
				}
			]
		},
		"2871": {
			"mode": 0,
			"parts": [0],
			"liveries": [{
					"name": "Air Malta",
					"texture": "https://raw.githubusercontent.com/iuhairways/test/main/airmalta320neo.jpg"
				},
				{
					"name": "Lufthansa",
					"texture": "https://i.ibb.co/8X8wrvV/lufthansa.png"
				}
			]
		}
	}
}`

**Comment by iuhairways** [comment]
ok thank you so much
