### ISSUE TITLE
Singapore Airlines A350-900

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#35]
![singapore](https://user-images.githubusercontent.com/103064103/192112997-30e5d564-58bc-4a03-b6a9-aed4f0748c6a.jpg)

**Comment by Ryubunao** [comment]
btw why did people make the text flipped on the other side of the plane??

**Comment by kolos26** [comment]
> btw why did people make the text flipped on the other side of the plane??

For some aircrafts you need to flip the text on the bottom one. Mostly for those texture files, where all the tails are both on the right.

**Comment by Ryubunao** [comment]
Ohhhh ok
Like the 767?
