### ISSUE TITLE
Request: British Airways ERJ120

### ISSUE THREAD

**Issue by SkyvaAirways** [kolos26/GEOFS-LiverySelector#351]
hi, i made the british airways livery (i not make the wing bc its original colors) and my crj200 liveries lagging and added air canada please fix that
![ba](https://github.com/kolos26/GEOFS-LiverySelector/assets/127486792/fae53b2f-5064-42a6-adad-13811187399f)

**Comment by kolos26** [comment]
Thanks the erj120 might take a few days to test out, how to add it to ls

**Comment by kolos26** [comment]
It's for the erj170, but it's active now :)
