### ISSUE TITLE
Can't select livery's

### ISSUE THREAD

**Issue by wvzackscratch** [kolos26/GEOFS-LiverySelector#352]
I can not change the livery for some reason maybe i am doing something wrong? Thanks.

**Comment by kolos26** [comment]
Sorry about that, GeoFs 3.6 is just out, and it's not really working yet. The builtin livery chooser is also off. It should be fixed in a few days.

**Comment by wvzackscratch** [comment]
Okay, Thanks for the quick response. I like your addon/thingy it will be
way easier than going in the inspect element to change to ryanair before
crashing :).

**Comment by kolos26** [comment]
I have fixed the bug. Please update LiverySelector.
[https://github.com/kolos26/GEOFS-LiverySelector/releases/tag/v2.0.3](https://github.com/kolos26/GEOFS-LiverySelector/releases/tag/v2.0.3)
Thank you for using LiverySelector!
Kolos26
