### ISSUE TITLE
A380-800 Qatar airways

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#38]
![image](https://user-images.githubusercontent.com/103064103/192117649-0bfe68db-6824-4cfe-8b20-4a3c5ba22bb9.png)

**Comment by iuhairways** [comment]
Uh, 
![image](https://user-images.githubusercontent.com/103064103/192116423-1c1c06d1-c742-46e2-8be6-a95cc87c410e.png)

**Comment by iuhairways** [comment]
when you add it can you try fixing that

**Comment by airgeorge** [comment]
do you have the base map for this?

**Comment by iuhairways** [comment]
i used airfrance 
![image](https://user-images.githubusercontent.com/103064103/192161158-e8d238c9-3ea8-4a11-9455-6934e11a0788.png)

**Comment by airgeorge** [comment]
thank you!

**Comment by iuhairways** [comment]
np
