### ISSUE TITLE
How to have my own liveries in a "private livery selector" ?

### ISSUE THREAD

**Issue by Egan-31** [kolos26/GEOFS-LiverySelector#385]
Hi, I would like to fly with the different liveries i've created before sharing it with others to check if there is any mistakes or bugs, and to create some liveries to myself. But, Idk how to create my "own" livery selector modifing the code in the console. So, kolos, or someone else, could you give me some tips to to do it ? 
Thanks !!

**Comment by kolos26** [comment]
Sorry for not responding, I was on holiday.
I'm using the loadLivery function from console for testing.
You can use it like this:
Post the livery out at https://imgbb.com/ and copy the image url.
loadLivery([link], [index], [parts])
you can look up the index and parts number in the livery.json for every aircraft
generally on the aircrafts by spice9 it's 0 0 (ATR too)
on Xavier's planes index 3 parts 0 (There are differences!)

For more complex planes (multiple parts, multiple textures) you can also check the livery.json (or inspect element on the buttons), but these are not that common (who wants to draw 3 different texture file (except me :) ) )
I agree in that a proper testing function should be implemented in the next version of LS.

**Comment by Egan-31** [comment]
Thank you very much kolos.
Yes it would be a great idea for an update of LS

**Comment by Egan-31** [comment]
I've just tried, but idk why it doesn't work.

**Comment by a321neofan** [comment]
Having a thing where you can make your own liveries that only you can use would be great.

**Comment by kolos26** [comment]
> Having a thing where you can make your own liveries that only you can use would be great.

I was thinking on this, but I rejected this idea, because this may cause that users won't share their liveries with the community, which is the mechanism that keeps the project alive. If the virtual airlines version of geofs came out (until december I suppose) you will have the option to create a "virtual airline" for yourself and use it as a testbed / personal stuff.

**Comment by a321neofan** [comment]
Oh ok
