### ISSUE TITLE
May I join your creation？

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#417]
Can you take China Eastern Airlines for 777w.and How do I paint and send it to you?

**Comment by PilotKetchum** [comment]
Yes You May Join In Discord Server Or I Can Make This One!

**Comment by 1414841886** [comment]
> 是的，您可以加入 Discord 服务器，或者我可以制作这个！

please you make this,thank you very much

**Comment by 1414841886** [comment]
> Yes You May Join In Discord Server Or I Can Make This One!

I am a video producer in China， my fans play this game and they want to play chinese uniform.So do you occasionally have to make aircraft coatings for Chinese airlines?

**Comment by 1414841886** [comment]
Please be sure to refer to the pictures of the real aircraft, if the Chinese and registration number on the wings can be added, please add them

**Comment by 1414841886** [comment]
@PilotKetchum hello?

**Comment by PilotKetchum** [comment]
> @PilotKetchum hello?

There I Made China Eastern B777

**Comment by 1414841886** [comment]
> > 你好？
> 
> 在那里我做了中国东方航空B777

i see,thanks,could you tell me how to make it?i want to make more and more.
