### ISSUE TITLE
LIVERY SUBMISSION：CHINA EASTERN A350-900(1st A350 delivered form China livery）

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#440]
1st is 4096,2nd is 2048
![m_CHINA EASTERN A350-900(1st A350 delivered form China） (2)](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/a50014be-2541-4b06-af27-60c38bba5613)

![m_CHINA EASTERN A350-900(1st A350 delivered form China）](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/499cafde-aa25-4de1-8258-8a042dba59be)
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/636c1aaf-7b68-44d1-94f1-c4264e0c3486)

**Comment by 1414841886** [comment]
@kolos26 i did not see it in game?

**Comment by kolos26** [comment]
This one will be solved tomorrow, others should work now

bili-開飛機のzm ***@***.***> ezt írta (időpont: 2024. jan. 16., K
1:48):
