### ISSUE TITLE
I am a video producer. Can I add a small watermark under the wing? I want my fans to know that I made it.

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#444]

**Comment by kolos26** [comment]
Technically you can, but I wouldn't recommend to do that, 'cause the wing is always a mirrored part, so it won't look to great. This is the same problem with registrations, they will only look good on one wing.

**Comment by 1414841886** [comment]
> Technically you can, but I wouldn't recommend to do that, 'cause the wing is always a mirrored part, so it won't look to great. This is the same problem with registrations, they will only look good on one wing.

do you want to me do it?I listen to you
