### ISSUE TITLE
LIVERY SUBMISSION：Air New Zealand ATR 72 - 600

### ISSUE THREAD

**Issue by Xab-Aras** [kolos26/GEOFS-LiverySelector#447]
First try - Let me know if correct.

![atr72 ANZ](https://github.com/kolos26/GEOFS-LiverySelector/assets/156680269/1c552a11-ad0c-4412-abcd-13bf8153aec8)

**Comment by kolos26** [comment]
nice one as a first try!

**Comment by Xab-Aras** [comment]
Oh, Thanks Kolos!

**Comment by kolos26** [comment]
Now you can go and try it out :)
