### ISSUE TITLE
Korean Air A380

### ISSUE THREAD

**Issue by airgeorge** [kolos26/GEOFS-LiverySelector#45]
Korean Air A380.
sorry if this is a bit low quality,this is my first A380 livery and i was trying out a new program.
![image](https://user-images.githubusercontent.com/112053353/192386775-8a176621-da69-4b60-89a3-b95df5681154.png)

**Comment by Ryubunao** [comment]
Nosatalgia intensifies

**Comment by BoeingBus747** [comment]
We have A380 maps now?

**Comment by kolos26** [comment]
No, we use the air france texture, because that is enough white.

https://user-images.githubusercontent.com/103064103/192161158-e8d238c9-3ea8-4a11-9455-6934e11a0788.png

**Comment by BoeingBus747** [comment]
oh! So that's how they make liveries for it,okay

**Comment by femifadina** [comment]
it lookes good
