### ISSUE TITLE
LIVERY SUBMISSION again：XIAMEN AIR B737-800(SKEAM),CHUNQIU AIRLINES A320NEO,XIAMEN AIR (UN livery)

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#457]
I've switched places for the next two，CHUNQIU livery: Please adjust the logo on the wings
![XIAMEN AIR B737-800(SKYEAM)](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/1b54d7bb-e878-4cf9-a0e5-ddd88e32e141)
![CHUNQIU AIRLINES A320NEO](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/f35d1678-dadd-48df-9e15-1bf45ebf6aae)

Xiamen I changed "BOEING B787-9" to white
![xiamen789](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/00b728a1-36c4-49c2-abff-89929248e97f)
thanks！

**Comment by 1414841886** [comment]
@kolos26 I found some of the livery I made in the game that need to be optimized, I want to add my watermark on the stomach, can I modify it again and send it to you?

**Comment by kolos26** [comment]
Yh

**Comment by 1414841886** [comment]
> Yh

ok
