### ISSUE TITLE
LIVERY SUBMISSION again：XIAMEN AIR B787-9(UN),CHINA EASTERN A350-900(1st A350 delivered form China),JUNEYAO B787-9

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#458]
Xiamen Airlines 787-9 I missed a sentence in the body when I first made it（Please adjust the resolution of xiamen to a little smaller）
![xiamen](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/f7fea1d6-0258-4ffd-8bf5-2465186eb473)
CHINA EASTERN,The first time I made it, I spelled the word "from" on the body as "form", and I have corrected it
![CHINA EASTERN A350-900(1st A350 delivered form China）](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/461a2742-dc11-4799-a427-509ff46fe943)

Juneyao Airlines B787-9, I found that the LOGO on the rear wing was big in the game, so I changed it to a smaller one
![JUNEYAO AIRLINES B787-9(YuanShen)](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/853f2e7f-7b8a-46b5-b8dd-88e4aa38473a)
I've added my logo to the bottom of them.
Thank you for doing so much for my liveries, and I thank you on behalf of my fans!

**Comment by 1414841886** [comment]
@kolos26 Chunqiu A320neo, Sichuan A320neo, Chunqiu A321neo, Xiamen B787-9(UN), I can't load them out, can you adjust the resolution?

**Comment by 1414841886** [comment]
@kolos26 Chunqiu A320neo, Sichuan A320neo, Chunqiu A321neo, Xiamen B787-9(UN), I can't load them out, can you adjust the resolution?

**Comment by 1414841886** [comment]
@kolos26 if you fix them please tell me thank you

**Comment by kolos26** [comment]
I have tested them, they should work now

**Comment by kolos26** [comment]
This one should be 1024*1024

**Comment by 1414841886** [comment]
> I have tested them, they should work now

Thank you for doing so much for me

**Comment by 1414841886** [comment]
@kolos26 But did you re-upload them?

**Comment by 1414841886** [comment]
@kolos26 Please let me know when you re-upload my revised livery, thank you.
