### ISSUE TITLE
LIVERY SUBMISSION ：AIR CHINA B737-800(STAR ALLIANCE)

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#459]
![738](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/eb78a061-c800-4d6e-90d5-f4846363af54)
![833235_1704518065](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/49cb840f-32d7-49aa-b83f-429cf533bb25)

**Comment by 1414841886** [comment]
@kolos26  Please adjust the logo on the wings

**Comment by kolos26** [comment]
Hi,
I would like to show you how can properly adjust textures.
This thing is called a uv map, and it identifies what parts of the texture file are projected on the 3d model, most likely, when you are wrapping presents. In gimp, you can add it as a layer, and you will find the position of the winglets easily.
[https://ibb.co/sFVbLzN](https://ibb.co/sFVbLzN) - a320n
[https://ibb.co/rmTwMG6](https://ibb.co/rmTwMG6) - b738 
Best regards,
Kolos

PS, this one is done

**Comment by 1414841886** [comment]
@kolos26 I see thanks,please fix my liveries!

**Comment by 1414841886** [comment]
> Hi, I would like to show you how can properly adjust textures. This thing is called a uv map, and it identifies what parts of the texture file are projected on the 3d model, most likely, when you are wrapping presents. In gimp, you can add it as a layer, and you will find the position of the winglets easily. https://ibb.co/sFVbLzN - a320n https://ibb.co/rmTwMG6 - b738 Best regards, Kolos
> 
> PS, this one is done

please give me a321neo,i should fix chunqiu a321neo

**Comment by 1414841886** [comment]
> Hi, I would like to show you how can properly adjust textures. This thing is called a uv map, and it identifies what parts of the texture file are projected on the 3d model, most likely, when you are wrapping presents. In gimp, you can add it as a layer, and you will find the position of the winglets easily. https://ibb.co/sFVbLzN - a320n https://ibb.co/rmTwMG6 - b738 Best regards, Kolos
> 
> PS, this one is done

emm，do you have A321neo UV map?

**Comment by kolos26** [comment]
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/77933334/58c4aaa1-f077-44a9-8225-556f550fad4d)
