### ISSUE TITLE
Lufthansa A380 (Old Livery) (Livery Request)

### ISSUE THREAD

**Issue by Ryubunao** [kolos26/GEOFS-LiverySelector#46]
Hello! It's the first time I did a380 livery. heh. I didn't add a registration and the grey paint on the belly of the plane because it's difficult. The registration I was trying to make is D-AIMM. I did this livery because almost everytime I see the Lufthansa Technik Philippines Hangar in RPLL, I saw a Lufthansa A380 parked there. Sometimes there is even a Korean Air A380 or Asiana Airlines A380. Thanks :D

I'm also planning to make basic liveries, like the Cebu Pacific B757, or Cathay Pacific A350-1000. But who knows?
![Lufthansa](https://user-images.githubusercontent.com/114277365/193405429-969fd847-079d-44bf-8deb-daa063d4328f.png)

**Comment by Ryubunao** [comment]
I only added the flag not the callsign lmao

**Comment by kolos26** [comment]
I will fix that parts asap

**Comment by kolos26** [comment]
"I saw a Lufthansa A380 parked" Happily, they may will fly again :)

**Comment by Ryubunao** [comment]
I also saw a British Airways A380 in the hangar and also a Lufthansa Cargo B777F (New Livery) today lol

**Comment by Ryubunao** [comment]
but Lufthansa doesn't fly here to Manila Daily. There is only 1 european airline that flies to Manila daily. It's KLM. Amsterdam to Manila via Bangkok.

**Comment by Ryubunao** [comment]
why is my livery not in the game yet?

**Comment by kolos26** [comment]
Some fixes needed, sorry about that

**Comment by Ryubunao** [comment]
oh ok
