### ISSUE TITLE
LIVERY SUBMISSION ：SPRING AIRLINES B737-800

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#466]
![738](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/87d40460-a914-4beb-b74f-c41fd377247a)
![123524d0eed9b7712c7bd5c43c965d16](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/51154c57-0d68-4c9d-88a6-c7fbd9e35c2c)

**Comment by 1414841886** [comment]
@kolos26 Could you tell me the resolution of A350-900, A320neo, A321neo, B777-300ER, B737-800 and B737MAX8？

**Comment by kolos26** [comment]
- a359 4096*4096
- a320n 2048*2048
- a321n 2048*2048
- b773 4096*4096
- b738 1024*1024
- max8 1024*1024
