### ISSUE TITLE
lufthansa crj-700

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#47]
![lufthansaregional](https://user-images.githubusercontent.com/103064103/193406093-01118f7a-d390-4920-a607-60f1de2d3b03.jpg)
![crj](https://user-images.githubusercontent.com/103064103/193406096-9a7fca2f-6661-4f8c-a715-5519a3a516a1.jpg)

**Comment by Ryubunao** [comment]
2 Lufthansa submitted at the same hour. Nice

**Comment by iuhairways** [comment]
Noice

**Comment by iuhairways** [comment]
wait i forgot the other one 
![crj1](https://user-images.githubusercontent.com/103064103/193416056-6e15a962-759d-4e1f-a57a-8c5622d82d55.jpg)
