### ISSUE TITLE
Do you have b787-9 UV map?

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#476]

**Comment by 1414841886** [comment]
@kolos26 Hmmm，can you help me find it?
![IBYA1A @LOUXOJ344CEGS@R](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/5601db3a-7464-4f7f-baeb-82278310b954)

**Comment by kolos26** [comment]
The car is (temporary ?) removed
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/77933334/3380c5c1-3bcd-495a-9538-c7f773a850c4)
