### ISSUE TITLE
Livery Request

### ISSUE THREAD

**Issue by GPTbest** [kolos26/GEOFS-LiverySelector#496]
The BAe systems avro RJ100 is a elegant jet, but for now, It retired in most of the airlines :(
I don't know whether my comment can be seen but
If you can
Please, add some liveries for the RJ100,
Although it might gone in our life
but it's not gone, if someone remembers it.

Pls
add some liveries

**Comment by kolos26** [comment]
It's currently impossible. Sorry.

**Comment by GPTbest** [comment]
it's ok, but still thanks :)
