### ISSUE TITLE
LIVERY Sumbission: Air Canada Express ERJ170

### ISSUE THREAD

**Issue by CaptainDash8** [kolos26/GEOFS-LiverySelector#518]
https://ibb.co/bLxjW62
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/158066924/b1bbc96e-ba10-49e9-b517-0e1309b27acf)
https://ibb.co/KjXwPrx
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/158066924/8417384a-376b-4ca5-bdb2-f0f159476c2b)
https://ibb.co/dcSQJ93
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/158066924/4db4a6da-62c5-4943-b402-bb90a7493294)

**Comment by CaptainDash8** [comment]
@kolos26 I've attached a screenshot to illustrate what I am seeing

![Screenshot (45)](https://github.com/kolos26/GEOFS-LiverySelector/assets/158066924/45b683a3-b8d5-4d8f-96cd-267ac984c801)

**Comment by kolos26** [comment]
Sorry, it's been fixed
