### ISSUE TITLE
Where is Winglet located in the B737-700 map?

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#522]
Can you mark that?
![b737-700 (1)](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/f563af0e-5169-4a80-ade6-492efa3eba03)
and what is its resolution

**Comment by kolos26** [comment]
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/77933334/1b0d817a-a89e-4a2a-9ff6-0ee52b5d665e)
4096*4096
