### ISSUE TITLE
Can you mark the winglet bend on the map, I want to fix the winglet logo of Hainan Airlines and Hong Kong Airlines A359.

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#528]
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/4bfc890e-f8c7-4b20-9487-778867196548)

**Comment by kolos26** [comment]
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/77933334/1f13e42b-c94a-481f-a236-469c58176b22)

**Comment by kolos26** [comment]
The two grey are the outer ones

**Comment by 1414841886** [comment]
I mean, can you mark the bend of it
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/86c64e56-81be-42d9-af42-f39fc0c5e102)
