### ISSUE TITLE
CHINA SOUTHERN B787-9(787th BOEING 787 in the world Livery）

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#533]
![m_b789 (2)](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/bd84820f-f276-45d7-9677-50f8d2396de6)
![南方航空789](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/443743eb-679a-4c2f-997c-591e8eb63bc4)

**Comment by 1414841886** [comment]
@kolos26 When do you plan to fix the yellow line of Hainan Airlines and Hong Kong Airlines A359?

**Comment by 1414841886** [comment]
and is it possible for you to get a license for LRX?

**Comment by 1414841886** [comment]
do you konw free HD?forever

**Comment by kolos26** [comment]
> @kolos26 When do you plan to fix the yellow line of Hainan Airlines and Hong Kong Airlines A359?

Probably next week. I was busy 'cause of school.
