### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#545]
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/af441c6a-3746-4d35-8ae3-b0ee92229f56)

**Comment by kolos26** [comment]
[https://github.com/kolos26/GEOFS-LiverySelector?tab=readme-ov-file#how-to-use-the-test-feature](https://github.com/kolos26/GEOFS-LiverySelector?tab=readme-ov-file#how-to-use-the-test-feature)
