### ISSUE TITLE
CHINA EASTERN AIRLINES B777-300ER 

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#549]
![m_CHINA EASTERN AIRLINES B777-300ER](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/59e7fc5b-b286-4c7e-be93-f8ad9747ac5d)

**Comment by PilotKetchum** [comment]
> ![m_CHINA EASTERN AIRLINES B777-300ER](https://private-user-images.githubusercontent.com/154767397/304002250-59e7fc5b-b286-4c7e-be93-f8ad9747ac5d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTkwNTIsIm5iZiI6MTcwNzgxODc1MiwicGF0aCI6Ii8xNTQ3NjczOTcvMzA0MDAyMjUwLTU5ZTdmYzViLWIyODYtNGM3ZS1iZTkzLWY4YWQ5NzQ3YWM1ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMDA1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWEyZTExNDRiNGM2MDM1ZWRkMzk5YmQ1NzgyYWMzMWI5NDQwOGU3M2ZhODc0M2NmMmJmY2Y0NGNkNDUyN2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CFlirjQakTS-jjWRzhmdX1TLWjV65bxdz5-2Zp87Omk)

Hey I Made My Own China Eastern Airlines Though!

**Comment by 1414841886** [comment]
> > ![m_CHINA EASTERN AIRLINES B777-300ER](https://private-user-images.githubusercontent.com/154767397/304002250-59e7fc5b-b286-4c7e-be93-f8ad9747ac5d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTkwNTIsIm5iZiI6MTcwNzgxODc1MiwicGF0aCI6Ii8xNTQ3NjczOTcvMzA0MDAyMjUwLTU5ZTdmYzViLWIyODYtNGM3ZS1iZTkzLWY4YWQ5NzQ3YWM1ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMDA1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWEyZTExNDRiNGM2MDM1ZWRkMzk5YmQ1NzgyYWMzMWI5NDQwOGU3M2ZhODc0M2NmMmJmY2Y0NGNkNDUyN2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CFlirjQakTS-jjWRzhmdX1TLWjV65bxdz5-2Zp87Omk)
> 
> Hey I Made My Own China Eastern Airlines Though!

The author allows a higher quality livery of the same livery to be made again.
