### ISSUE TITLE
Could you upload it and then take a screenshot of it and show it to me in GeoFS, I want to know if it has errors, I want to do a better panda livery

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#554]
![m_T](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/06afb074-2637-437a-bcb3-71299b58c6bb)
![m_B-306N](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/bc3e6471-d47e-47e9-a50d-361a46cb04dc)
thanks！

**Comment by kolos26** [comment]
By pasting these links to the green box you can try it in 3d https://i.ibb.co/QJ4BkMy/305074738-06afb074-2637-437a-bcb3-71299b58c6bb.jpg and https://i.ibb.co/qMTnkd4/305085956-bc3e6471-d47e-47e9-a50d-361a46cb04dc.jpg

**Comment by 1414841886** [comment]
@kolos26 i can not see test plane,and please you solve my liveries qiukcily:)
