### ISSUE TITLE
SICHUAN AIRLINES A350-900 (Panda 2）

### ISSUE THREAD

**Issue by 1414841886** [kolos26/GEOFS-LiverySelector#557]
5.2MB！
I hope there are no errors in its connections.
![m_四川航空A350-900 p2](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/deb4c8cb-a36d-405e-8548-5524df87e921)
![306N 1](https://github.com/kolos26/GEOFS-LiverySelector/assets/154767397/70d0b6ea-b991-498e-b4d2-352d57499eaa)

**Comment by 1414841886** [comment]
@kolos26 Hi！I guess you saw this message should be at night, please upload it as soon as possible, by the way check if there is any error in its connection (bottom and body),my fans and i want to play it tomorrow in China,Approximately 8 hours behind where you are. thank you, have a nice time！

**Comment by kolos26** [comment]
Hi,
I'm in GMT+1, so it's afternoon here :) I have added your livery, but github, where the liveries are stored is really slow (at least here) now, so it might take minutes to load. (super annoying), so please note that before getting stroke (like I did yesterday)
Best regards,
Kolos

**Comment by kolos26** [comment]
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/77933334/69a8d7f4-d4d7-4e72-be87-33483adeb879)
I'm fixing these too, possibly released this week

**Comment by kolos26** [comment]
![image](https://github.com/kolos26/GEOFS-LiverySelector/assets/77933334/6614bc9e-ae7c-4109-b102-46a72c9554ef)
Turned out great!

**Comment by 1414841886** [comment]
> ![image](https://private-user-images.githubusercontent.com/77933334/305649056-6614bc9e-ae7c-4109-b102-46a72c9554ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTkwOTgsIm5iZiI6MTcwODI1ODc5OCwicGF0aCI6Ii83NzkzMzMzNC8zMDU2NDkwNTYtNjYxNGJjOWUtYWU3Yy00MTA5LWIxMDItNDZhNzJjOTU1NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDEyMTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NzY5OThiZDVkYmM2N2QxNzY2YWNjOGQ1ZWE5MzNkMjFiNWEyZWJmMDdmNzMzMzIxZjhkNTI0M2UxM2M5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1M_xSE2x2ERzeJ08P1YQ4ZfpTAbARYGPf6K6WmMJ6lo) Turned out great!

I envy you for having HD ：（
