### ISSUE TITLE
Some ATR 72 liveries (Livery Request)

### ISSUE THREAD

**Issue by Ryubunao** [kolos26/GEOFS-LiverySelector#56]
I noticed there were some mistakes in my American Eagle. So I decided to align it. And there is also a grey thing in the bottom of the plane. So I added extra lines. Btw I can't make the TransAsia livery since I can't find the stripes. And the current Iran Aseman Airlines livery. Since I also can't find the stripes. 

Liveries I make:
TransAsia Flight 791
TransAsia Flight 222
UTair Flight 120
Lao Airlines 301

Comment if what liveries should I make next!!
![American Eagles ATR 72-500 png (eee)](https://user-images.githubusercontent.com/114277365/193953210-365c4b20-2208-4257-b850-8d9c99afcdac.png)
![TransAsia Airways ATR-72-200 (Flight 791)](https://user-images.githubusercontent.com/114277365/193953234-263f595d-ea04-4b46-8094-4b5618c19b6c.png)
![TransAsia Airways ATR-72-200 (Flight 222)](https://user-images.githubusercontent.com/114277365/193953244-a361f10f-ed73-467e-a645-d16f68af6e8e.png)
![UTair ATR 72-200 (Flight 120)](https://user-images.githubusercontent.com/114277365/193953252-e3f6c8ac-fb8a-4687-b6c6-fb16bbb8bf0e.png)
![Lao Airlines ATR-72-600 (Flight 301)](https://user-images.githubusercontent.com/114277365/193953263-d6b771d6-6367-4f1e-8908-2940550b2ccd.png)

**Comment by Ryubunao** [comment]
Btw I can't see my Tuninter ATR 72

**Comment by kolos26** [comment]
I've added these, and fixed tuninter. For difficult textures, you can see a reference here: https://www.juergenbaumbusch.de/
