### ISSUE TITLE
Singapore Airlines A380-800

### ISSUE THREAD

**Issue by Egan-31** [kolos26/GEOFS-LiverySelector#58]
Hi everyone, I just made my first ever livery on GeoFS, so if there is any issue or tip to improve myself, you can send me a message.
Enjoy flying with it.
![A380-800_SA](https://user-images.githubusercontent.com/115219384/194517961-16bf2368-9ad9-4705-81d1-04707152ff5b.jpg)

**Comment by kolos26** [comment]
Beautiful livery! Thanks for doing this. Welcome to the community!

**Comment by Ryubunao** [comment]
Bruh you're better than me lol
