### ISSUE TITLE
Which location is the left side and the right side of the B787-9 map? (Help)

### ISSUE THREAD

**Issue by Ryubunao** [kolos26/GEOFS-LiverySelector#60]
Idk which is the left one. Top or bottom. Same goes for the right. So can you explain which side is the top one and which side is the bottom one?? thx
![B787-9](https://user-images.githubusercontent.com/114277365/194638104-787c6303-67f5-4780-b4a4-dd1139f63781.jpg)

**Comment by airgeorge** [comment]
top is left and bottom is right,flip the text on the bottom also.

**Comment by Ryubunao** [comment]
aahhhh thanks
