### ISSUE TITLE
HERE'S THE PROOF - I Made An Refreshed Version Of EVA Air Boeing 777-300ER

### ISSUE THREAD

**Issue by PilotKetchum** [kolos26/GEOFS-LiverySelector#633]
![Screenshot (17)](https://github.com/kolos26/GEOFS-LiverySelector/assets/32456371/8a16a3ac-abfc-4470-8162-2b1b991328ac)
Star Alliance Logo

![(62) PARADISE - Coldplay  edit audio 💫 - YouTube - Google Chrome 06_05_2024 10_58_37 pm](https://github.com/kolos26/GEOFS-LiverySelector/assets/32456371/530060a9-c819-44f7-ad47-a9384ad6a2d2)
Registration Number Of Eva Air Boeing 777-300ER

![EvaB777 (WithStarAllianceLogo)](https://github.com/kolos26/GEOFS-LiverySelector/assets/32456371/5354f69b-78b8-4cd2-b87c-4017ad48dfdf)
Refreshed Version With Evergreen Group Logo
Original Livery & Credits To @randomgeofsplayer 
I Made An Refreshed Version So I Can Replaced It Please @kolos26 Can You Replace It!

**Comment by randomgeofsplayer** [comment]
You may have added a couple things, but the base is the livery that I made. You should not be passing off a livery I made as completely your own without credit.

**Comment by PilotKetchum** [comment]
> You may have added a couple things, but the base is the livery that I made. You should not be passing off a livery I made as completely your own without credit.

SHUT THE FUCK UP!

**Comment by PilotKetchum** [comment]
> You may have added a couple things, but the base is the livery that I made. You should not be passing off a livery I made as completely your own without credit.

Hey Busy?

**Comment by randomgeofsplayer** [comment]
what do you want? If you really want a refresh that bad, I might make it, but stealing it is not ok.

**Comment by PilotKetchum** [comment]
> You may have added a couple things, but the base is the livery that I made. You should not be passing off a livery I made as completely your own without credit.

IF YOU DON'T CARE I'LL BLOCK YOU AGAIN!

**Comment by PilotKetchum** [comment]
> what do you want? If you really want a refresh that bad, I might make it, but stealing it is not ok.

I'm NOT STEALING!

**Comment by randomgeofsplayer** [comment]
don't do stuff with the livery I made without permission and credit
