### ISSUE TITLE
Boeing 737-700 Turkish

### ISSUE THREAD

**Issue by Egan-31** [kolos26/GEOFS-LiverySelector#65]
HI, even if know that Turkish airlines uses 737-800, i decideed making an new livery.
It twont be as precise as the work i done on the singapore a380, but i hope you'll find it correct. If it's not or if you've any adice, i take everything.
![b737-700_Turkish](https://user-images.githubusercontent.com/115219384/194698428-e6856157-c954-439a-9d6e-6373175164e4.png)

**Comment by Ryubunao** [comment]
they should operate B737-700s
