### ISSUE TITLE
Boeing 737-200 Viação Aérea São Paulo & ATR72-600 China Xinjiang Airlines(fictional)

### ISSUE THREAD

**Issue by 5527635** [kolos26/GEOFS-LiverySelector#657]
https://imgbb.host/images/vasp.png
![微信图片_20240531223602](https://github.com/kolos26/GEOFS-LiverySelector/assets/170812341/64d19dae-51ae-4896-8cc9-0f1ed31cd3fa)

https://imgbb.host/images/chinaxinjiang.png
![微信图片_20240531223609](https://github.com/kolos26/GEOFS-LiverySelector/assets/170812341/f52fbbe2-435b-4587-8b1e-95e75189819c)

**Comment by 1414841886** [comment]
good work bro Can you do other Chinese livery

**Comment by 5527635** [comment]
> good work bro Can you do other Chinese livery
thank you very much and this is my planned livery

**Comment by 5527635** [comment]
> good work bro Can you do other Chinese livery

thank you very much and i'm going to do some CAAC livery
