### ISSUE TITLE
Emirates Dubai Expo (Blue) Livery

### ISSUE THREAD

**Issue by airgeorge** [kolos26/GEOFS-LiverySelector#67]
ill have some more A380 liverys here.
![image](https://user-images.githubusercontent.com/112053353/194711949-4036c91a-d0f9-4456-a6df-35c97d3e9c0c.png)

**Comment by iuhairways** [comment]
nice

**Comment by airgeorge** [comment]
Malaysia Airlines A380.
![image](https://user-images.githubusercontent.com/112053353/194723970-1d2e73f4-9901-4fd8-8552-110267a989e8.png)

**Comment by randomgeofsplayer** [comment]
the windows on both of those are covered...
