### ISSUE TITLE
Etihad Partial Livery (Edited)

### ISSUE THREAD

**Issue by BoeingBus747** [kolos26/GEOFS-LiverySelector#71]
![AirFranceTexture - Copy](https://user-images.githubusercontent.com/114799770/194766111-e68a397d-6a8d-402f-a7eb-46332f6e01c6.png)

**Comment by BoeingBus747** [comment]
One sec, here use this one
![AirFranceTexture - Copy](https://user-images.githubusercontent.com/114799770/194766214-97a8b770-9d64-4415-8e2f-cfde505619ba.png)

**Comment by kolos26** [comment]
Updated :)
