### ISSUE TITLE
AIR CANADA 1930S TRANS CANADA AIR LINES 777-300ER (WITH SPECULAR SHADERS BARE METAL EFFECT) PLS ADD

### ISSUE THREAD

**Issue by SolAva8** [kolos26/GEOFS-LiverySelector#773]
![TCA 777](https://github.com/user-attachments/assets/9a3b9297-33ca-430d-8843-e6570829fcc8)
![TCA 777 DONE](https://github.com/user-attachments/assets/2c8b2753-3d90-4a07-b370-c2748253dc38)

**Comment by kolos26** [comment]
Ok, added
