### ISSUE TITLE
united 767-300 UPDATED cuz it is inverted

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#8]
![imageoknd](https://user-images.githubusercontent.com/103064103/186868517-d05066f5-76d6-46f7-b0e1-99f0f47cc013.png)

**Comment by iuhairways** [comment]
pleas delete other united

**Comment by kolos26** [comment]
I have updated your livery

**Comment by iuhairways** [comment]
k
