### ISSUE TITLE
Forgotten Repaints to be added.

### ISSUE THREAD

**Issue by Philavia744** [kolos26/GEOFS-LiverySelector#824]
![355305174-cfcf5f67-d5d8-4aff-a364-7370201160e0](https://github.com/user-attachments/assets/f20c3eac-ed55-4151-8af0-f59daacfcd4c)
(Airasia Zest after Zest Airways merged into Airasia)
![355305305-d308ad3a-fbaa-45f6-96d7-92bd028828a9](https://github.com/user-attachments/assets/f38999af-cf78-4e2d-b153-1bfff8a65410)
Puregold hypermart chain here in the Philippines, Airasia has a livery of it. 
![353286323-706c1748-1bac-4b19-8437-4992837f3b62 (1)](https://github.com/user-attachments/assets/5c669687-fcef-4e15-a59d-2b27883556e1)
Royal Air Philippines with old tourisim stickers and another major airline in the philippines

**Comment by CaptainAshAdult** [comment]
> ![355305174-cfcf5f67-d5d8-4aff-a364-7370201160e0](https://private-user-images.githubusercontent.com/164663549/358634193-f20c3eac-ed55-4151-8af0-f59daacfcd4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTU4OTcsIm5iZiI6MTcyMzg5NTU5NywicGF0aCI6Ii8xNjQ2NjM1NDkvMzU4NjM0MTkzLWYyMGMzZWFjLWVkNTUtNDE1MS04YWYwLWY1OWRhYWNmY2Q0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMTUzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWI4NjgyOTljNjI0OTUyODU1MTkzMGI5ZTcyZWFkYzIwODFkYjM2M2FmOWI2ODRhNDMxZmQ1NTg5YzMwMjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rSUm6CnVZKNjVxmeZXwp7BnwRpszt1lfiuFMbb8VmXQ) (Airasia Zest after Zest Airways merged into Airasia) ![355305305-d308ad3a-fbaa-45f6-96d7-92bd028828a9](https://private-user-images.githubusercontent.com/164663549/358634313-f38999af-cf78-4e2d-b153-1bfff8a65410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTU4OTcsIm5iZiI6MTcyMzg5NTU5NywicGF0aCI6Ii8xNjQ2NjM1NDkvMzU4NjM0MzEzLWYzODk5OWFmLWNmNzgtNGUyZC1iMTUzLTFiZmZmOGE2NTQxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMTUzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTAzZThhNWYxNjM3NDgzNjkwMGEwYjM2OTZkYTkxZmFkMzE2YTY5M2Y1NWY3MmVmZGI2ODNjODdiNDcyZWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jFPB44k8fuEwuckELEIVz0v0oz5qvpmqVVK9lIJeBZ8) Puregold hypermart chain here in the Philippines, Airasia has a livery of it. ![353286323-706c1748-1bac-4b19-8437-4992837f3b62 (1)](https://private-user-images.githubusercontent.com/164663549/358634539-5c669687-fcef-4e15-a59d-2b27883556e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTU4OTcsIm5iZiI6MTcyMzg5NTU5NywicGF0aCI6Ii8xNjQ2NjM1NDkvMzU4NjM0NTM5LTVjNjY5Njg3LWZjZWYtNGUxNS1hNTlkLTJiMjc4ODM1NTZlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMTUzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGQxMDBjODE2ODE3ODA4NjkzZDI3MWFiNDNkMTZhOTAwOWVjZDVkMTI3OGYyMDBjZmJjNmE5ZjUwYWExN2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WbkRz0Li24sbE51qbnzMSSfjA_rz4deEdN3W4k5DNK4) Royal Air Philippines with old tourisim stickers and another major airline in the philippines

Yeah @kolos26  Would You Add This?

**Comment by kolos26** [comment]
@Philavia744 Can you please submit them as 2048*2048 images next time? It's really annoying to resize them all the time
