### ISSUE TITLE
Do you have a template for A330-200? Can you give it to me

### ISSUE THREAD

**Issue by HO1076** [kolos26/GEOFS-LiverySelector#828]

**Comment by CaptainAshAdult** [comment]
> _No description provided._

Same Here I Needed It?

**Comment by kolos26** [comment]
![image](https://github.com/user-attachments/assets/99bfee25-28fe-4a4f-b315-00ffa6ff6e8f)
![image](https://github.com/user-attachments/assets/f19a6081-9ec2-46c4-98fd-91ad42c376d7)
