### ISSUE TITLE
Airbus A380 Emirates new livery problem

### ISSUE THREAD

**Issue by aviationgeek1** [kolos26/GEOFS-LiverySelector#833]
Hello there, I hope this message finds you well. There seems to be a problem with Emirates A380 new livery. At the bottom of the aircraft ,it is always written Emirates in white with a red background. But in the livery this cannot be seen. Please fix this as soon as possible and I hope to hear from you soon.

Regards, 
aviationgeek1

**Comment by kolos26** [comment]
I'm gonna fix it in this update
