### ISSUE TITLE
THis is the new b777-300er philippine airlines I resize the font

### ISSUE THREAD

**Issue by andymance** [kolos26/GEOFS-LiverySelector#852]
![philippines](https://github.com/user-attachments/assets/dc7f271a-fd2e-4931-b0a4-630a952bf92b)

**Comment by CaptainAshAdult** [comment]
> ![philippines](https://private-user-images.githubusercontent.com/140888717/362215267-dc7f271a-fd2e-4931-b0a4-630a952bf92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODYwNTUsIm5iZiI6MTcyNDg4NTc1NSwicGF0aCI6Ii8xNDA4ODg3MTcvMzYyMjE1MjY3LWRjN2YyNzFhLWZkMmUtNDkzMS1iMGE0LTYzMGE5NTJiZjkyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQyMjU1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTI4YzFiMDg2Y2QxZWIyM2IzOTRhZDJjMzU0ZjIzYzZmMmQxNGM0ZWU3ZmJhMjllNmY4NjZhZmFlZjY4MGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1t8GMMJeBN64FW94lFS8Hi18hqj60qi2DdXOPpI7CcY)

Listen PhilAvia744 Made It Because Your Livery Of Philippine Airlines Sucks!

**Comment by CaptainAshAdult** [comment]
Can You Ban @andymance  On Livery Selector? He's Rigging This!

**Comment by CaptainAshAdult** [comment]
> ![philippines](https://private-user-images.githubusercontent.com/140888717/362215267-dc7f271a-fd2e-4931-b0a4-630a952bf92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mzg5MzgsIm5iZiI6MTcyNDkzODYzOCwicGF0aCI6Ii8xNDA4ODg3MTcvMzYyMjE1MjY3LWRjN2YyNzFhLWZkMmUtNDkzMS1iMGE0LTYzMGE5NTJiZjkyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMzM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmQ1ZjQ1YWQyZGU4ZGM3ODlkZGI5ZTBkMzkyZjMyNTk1OThhMWU5ZmM2NDUyZDAzMGM0NDZlMjU5ZmYwMjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ksvvONsG1XaNlxKdE17m1LsjHSGF4HxTDQeqo0C6GXM)

YOU'RE PEDO NOW!
