### ISSUE TITLE
kolos i have the a320-214 map. DONT CHANGE THE RESOLUTION

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#87]
![image](https://user-images.githubusercontent.com/103064103/196031288-c6b3e142-60ce-4acb-abe9-1721fd4545f4.png)

**Comment by Ryubunao** [comment]
Oh mah gawd!1!1!
U got da map!1!
fr

**Comment by Ryubunao** [comment]
He should make the all-white livery so I can make my livery there

**Comment by kolos26** [comment]
Sorry, but I couldn't get it work. We need to wait for the announced update.

**Comment by kolos26** [comment]
But I will try to rework the broken parts on the model, and add them via script like this: https://github.com/NVB9ALT/Addon-Aircraft-and-Parts

**Comment by iuhairways** [comment]
> Sorry, but I couldn't get it work. We need to wait for the announced update.

i think that its the wrong sizing
