### ISSUE TITLE
Airbus A380 Emirates New Livery Issue 

### ISSUE THREAD

**Issue by aviationgeek1** [kolos26/GEOFS-LiverySelector#875]
Subject: Missing UAE Flag on Emirates New Livery in GeoFS

Dear GeoFS - Livery Support Team,

I hope this email finds you well. I am an active contributor on GitHub and wanted to bring to your attention a small detail regarding the Emirates new livery in the simulator. It appears that the UAE flag is missing from the winglets of the Emirates aircraft. In reality, the Emirates livery includes the UAE flag on the winglets, and its absence in the simulator slightly detracts from the overall realism.

I understand that minor details can sometimes be overlooked, but I would really appreciate it if this could be corrected in a future update. It would enhance the experience for aviation enthusiasts who value accuracy in aircraft liveries.

Thank you for your time and consideration.

Best regards,
Aviation Geek 1

**Comment by SolAva8** [comment]
join the discord.

**Comment by kolos26** [comment]
Hi, you should consider joining to the discord, where you will most probably find someone to quickfix the livery. I don't usually have enough time to work on the liveries.
