### ISSUE TITLE
make liverys for the 747 pls

### ISSUE THREAD

**Issue by bananaairbus** [kolos26/GEOFS-LiverySelector#880]
there are no set liverys for the 747 the only one is cargolux

**Comment by dokifreyaroblox** [comment]
there is no template for the livery so people can't make liveries for it just yet

**Comment by bananaairbus** [comment]
k

**Comment by kolos26** [comment]
The creator of the 747 doesn't allow us to make new liveries for his planes. Sorry about that.

**Comment by thomaslfranca** [comment]
Hey kolos26
do you answer pull requests to?
Thanks by your attention.

**Comment by bananaairbus** [comment]
> The creator of the 747 doesn't allow us to make new liveries for his planes. Sorry about that.

ok thanks for letting me know
