### ISSUE TITLE
can we have 757 map?

### ISSUE THREAD

**Issue by iuhairways** [kolos26/GEOFS-LiverySelector#9]

**Comment by iuhairways** [comment]
@kolos26

**Comment by kolos26** [comment]
Thank you very much for your contribution!
You need to repaint the original texture file, for this aircraft, there is not really a map for it, but from the position of the doors, logos, etc. you can figure out where to paint what.

https://www.geo-fs.com/backend/aircraft/repository/GXD04N_126645_238/texture.png

**Comment by iuhairways** [comment]
k
