### ISSUE TITLE
VFA 41 "Black Aces" F18-F

### ISSUE THREAD

**Issue by Vansh-Vviation** [kolos26/GEOFS-LiverySelector#908]
SO, let me ask you real fast, what aircraft carrier is show cased in Geofs? Of course it's the CVN 74, or the USS John C. Stennis, and what squadron operated on the Stennis? Once again you are correct, one of the squadrons that operated off the Stennis was the VFA 41 squadron of the US Navy. This livery is based off the picture I will list below from when the squadron operated off the John C. Stennis. This aircraft in my livery and in real life is registered "166842".

Real life:
![image](https://github.com/user-attachments/assets/454e8405-68d3-47e5-bd41-ece83375bd42)

Texture:
![BLACK_ACES_VFA41](https://github.com/user-attachments/assets/ed6ee90f-7822-4532-8fe3-140c4ad60f8e)

screen shots:
![Screenshot 2024-11-03 5 27 19 PM](https://github.com/user-attachments/assets/efdc28fc-f9b1-4937-a4ef-cf8b5875c59a)
 
![Screenshot 2024-11-03 5 48 29 PM](https://github.com/user-attachments/assets/2c668626-f668-4708-9706-3b577f042a02)

Once again, hope y'all enjoy, My next livery im planning on making is the Top Aces Alphajet so stay tuned, and I will see you later! (Update) So i think I might delay the TA Alphajet for a Topgun livery for the F18-F which yes it was real.

**Comment by kolos26** [comment]
Thank you, no problem if you delay the alphajet livery, for a f18.
And I'm pretty sure you will love this add on: https://github.com/TotallyRealElonMusk/GeoFS-Extra-Maritime-Structures :)

**Comment by kolos26** [comment]
![fa18uvmap](https://github.com/user-attachments/assets/1f89d454-559f-4959-b4d1-6b08d1d9ad6e)
You might find this useful

**Comment by Vansh-Vviation** [comment]
Ah yes, thank you very much for informing me about the Maritime Structures add on, and also for providing the UV map for the f18!
